apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-forwarder
  labels:
    app.kubernetes.io/name: argus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: forwarder
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: forwarder
  ports:
    - name: http
      port: 80
      targetPort: http
