apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argus.forwarderServiceAccountName" . }}
  labels:
    app.kubernetes.io/name: argus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: forwarder
